### PR TITLE
Fix redis sentinel backend interface with cachelib

### PR DESCRIPTION
**Pull request by northernSage**
Follow up for of https://github.com/pallets-eco/cachelib/pull/159

This makes it so `flask_caching.backends.RedisSentinelCache` can `flask_caching.backends.RedisClusterCache` will now override `cachelib.RedisCache._write_client` and `cachelib.RedisCache._read_client `, addressing the problem described in #362

- [x] override read/write clients from `RedisSentinelCache`
- [x] add changelog
- [x] update package requirements in `setup.py` and requriements dir
- [x] add tests covering bug for RedisSentinelCache

### CODE REVIEW

**Comment by quito-inv** [comment]
Hi, was this fix released? I am not seeing it in the changelog and I'm getting this error that looks like is fixed by this PR
```
.venv/lib/python3.8/site-packages/flask_caching/backends/rediscache.py", line 62, in __init__
    self._write_client = self._read_clients = self._client
AttributeError: 'RedisCache' object has no attribute '_client'
```
This error happened after upgrading to v1.11.1 from v1.11.0. 

I think this PR fixes it but is it possible that it wasn't released?

**Comment by northernSage** [comment]
@quito-inv this has been release in [2.0.0](https://github.com/pallets-eco/flask-caching/blob/master/CHANGES.rst#version-200) along with other improvements/fixes.

**Comment by quito-inv** [comment]
@northernSage oh great, but that means that the latest v1.x are broken? Neither work, at least for me. In 1.11.0 I get an error because cachelib doesn't exist and in 1.11.1 I get the error I mentioned before
