### ISSUE TITLE
FileSystemCache not working in flask_caching 1.11.1

### ISSUE THREAD

**Issue by Rosadosa** [pallets-eco/flask-caching#364]
When trying to use: 
```
from flask_caching import Cache

CACHE = Cache(
    config={
        "CACHE_TYPE": "FileSystemCache",
        "CACHE_DIR": "cache",
        "CACHE_THRESHOLD": 10,
    },
)     
CACHE.init_app(server)
```

the following stack trace occurs.
```
 .venv/lib/python3.9/site-packages/flask_caching/__init__.py", line 141, in init_app
    self._set_cache(app, config)
.venv/lib/python3.9/site-packages/flask_caching/__init__.py", line 172, in _set_cache
    app.extensions["cache"][self] = cache_factory(
.venv/lib/python3.9/site-packages/flask_caching/backends/filesystemcache.py", line 79, in factory
    return cls(*args, **kwargs)
.venv/lib/python3.9/site-packages/flask_caching/backends/filesystemcache.py", line 59, in __init__
    CachelibFileSystemCache.__init__(
TypeError: __init__() got an unexpected keyword argument 'hash_method'
```

Using in a pyproject.toml file:
python = "^3.9"
flask = "^2.0.1"
flask-caching = " ^1.10.1"
flask-compress = "^1.10.1"
flask-session = "^0.3.2"

**Comment by gumptionthomas** [comment]
This could be due to an older installed version of [`cachelib`](https://pypi.org/project/cachelib/). The `hash_method` argument was added in version 0.6 (current version is 0.7). The `setup.py` for `flask_caching` doesn't specify a minimum version for `cachelib`.

**Comment by gumptionthomas** [comment]
You might want to pin your `cachelib` library to version 0.6.0 due to #363 .

**Comment by Rosadosa** [comment]
That seems to do the trick! Thanks, will close this, it is then related to your issue @gumptionthomas
